version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  thirdparty-api-avc:
    container_name: thirdparty-api-svc
    image: mojaloop/thirdparty-api-svc:local
    build:
      context: .
      cache_from:
        - mojaloop/thirdparty-api-svc:local
    ports:
      - "3008:3008"
    networks:
      - mojaloop-net
    volumes:
      - ./config:/opt/thirdparty-api-svc/config
    environment:
      - LOG_LEVEL=debug
    healthcheck:
      test: wget -q http://localhost:3008/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
